### PR TITLE
refact!: contact Gohan directly and remove Go server

### PR DESCRIPTION
**Pull request by davidlougheed**

### CODE REVIEW

**Review by gsfk — COMMENTED** [review]
cleaned, pulled, etc, and I'm still stuck here: 

`bentov2-public  | [bento_public] [entrypoint] starting NGINX`

... hangs forever after that

**Comment by davidlougheed** [comment]
oops, fixed.

**Review by gsfk — COMMENTED** [review]
working now in prod mode. In dev (with this branch checked out) I get this: 

```
bentov2-public  | <e> [webpack-dev-middleware] [Error: EACCES: permission denied, mkdir '/bento-public/dist/js'] {
bentov2-public  | <e>   errno: -13,
bentov2-public  | <e>   code: 'EACCES',
bentov2-public  | <e>   syscall: 'mkdir',
bentov2-public  | <e>   path: '/bento-public/dist/js'
bentov2-public  | <e> }

```
and then it hangs, all requests get "wait for build" in logs

`bentov2-public  | <i> [webpack-dev-middleware] wait until bundle finished: /
`

and instead of "Bad Gateway" in the browser I get `504 Gateway Time-out`.

**Comment by davidlougheed** [comment]
hmm, was working for me but probably due to a local setup bug - i'll check it out, thanks

**Review by gsfk — APPROVED** [review]

**Pull request merged**
